name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=4.0.9
  - seaborn=0.12.0
  - pandas=2.1.2
  - pip=23.3.1
  - pyarrow=2.0
  - pip:
      - wandb==0.15.12
      - ydata-profiling==4.6.2