name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3
  - matplotlib=3.8.2
  - pandas=2.1.3
  - requests=2.24.0
  - pip=23.3.1
  - mlflow=2.3.1
  - pip:
      - wandb==0.15.12
