name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.1.2
  - pip=23.3.1
  - mlflow=2.3.1
  - scikit-learn=1.3.2
  - pip:
      - wandb==0.15.12
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
