name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.1.2
  - pip=23.3.1
  - mlflow=2.3.1
  - scikit-learn=1.3.2
  - matplotlib=3.8.2
  - pillow=10.1.0
  - pip:
      - wandb==0.15.12
